FROM node:20-alpine

WORKDIR /app

# install docker CLI
RUN apk add --no-cache docker-cli

COPY package*.json ./
RUN npm install --production

COPY . .

CMD ["node", "src/features/execution/execution.worker.js"]